/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fc019cab-62aa-4c46-a3f7-c8fe64c69c23",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_InJQcYIev",
    "aws_user_pools_web_client_id": "4am4vuc6m346v78j52mrfjhgpg",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://otbrf533xzdzna25nqmcvew6ee.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-twg55f6vmbef5hfmi67szudlpm"
};


export default awsmobile;
